### PR TITLE
Settings reset button, prevent editing non-settings JSON files

### PR DESCRIPTION
**Pull request by iiPythonx**
Edit list:
- Rename `filesave.php` to `save_settings.php` and always save to `settings.json`
  - Including some basic JSON validation
- Add "reset configuration" button which calls `save_settings.php` with the content of `settings.sample.json`
- Add some margin to bottom of editor buttons (so they don't look squished anymore)

If this PR causes any problems, or if I added something that you don't want to merge, let me know :)

### CODE REVIEW

**Comment by erohtar** [comment]
Hey @iiPythonx -  really sorry for not getting back to you sooner. Work has been really busy so personal projects have taken a backseat..
Anyway, I got a chance to try out the changes and here's my feedback:

- Don't allow random JSON files to be edited: The 'random' JSON editing is actually by design as this allows multiple Dasherr homepages to co-exist without having to run whole instances separately. Also works as the main homepage can have a link to a sub-page (I personally use the main page for my home-server and one of the tiles leads to a sub-page for my cloud instance). Pls correct me if I'm wrong here, but it looks like this change breaks that functionality?
- Allow config reset from UI: This is really useful and cuts off the manual restore method. While saving with one click is the norm, I believe in this case the one thing that's really needed is a confirmation message before overwriting the current config. An accidental click while trying to click Save, or one curious click on Restore would lead to quite a bit of frustration for the user. What do you think? 

Thank you!

**Comment by iiPythonx** [comment]
@erohtar Thanks for getting back to me on it!
About the JSON file loading change, it doesn't affect loading in any way, so assuming you still had the proper configuration files, they should load fine. The original save JS had `settings.json` hardcoded as well, but I can double check.

~~Reset file wise, a confirmation would be great. I could implement a basic alert() based one if that works for you, otherwise I'll leave it up to you.~~

EDIT: Basic confirmation added in b7928c7. And according to [this line](https://github.com/erohtar/Dasherr/blob/main/www/include/editor_js.php#L28C43), the save action always overwrote `settings.json`, so my original commit shouldn't change anything.

**Comment by erohtar** [comment]
> And according to [this line](https://github.com/erohtar/Dasherr/blob/main/www/include/editor_js.php#L28C43), the save action always overwrote settings.json, so my original commit shouldn't change anything.

Yes! I was testing your updates and when I saw it always overwrote main config, I went back to check and found it was a bug in my original code. So I fixed it locally and came here to mention it to you and found your edit haha
Here's my simple fix to that line:
```
data.append('file' , settingsFile? '../' + settingsFile : '../settings.json');
```

I love that confirmation msg, and you're right, that basic alert is all that was needed. Btw the above mess points out a residual problem - if a user is editing a non-main settings file, and uses the reset config feature, the main config gets reset. That's not good. 
Any ideas? I was thinking maybe hiding the reset button on non-main config editor or showing a simple alert that says this feature is only for settings.json resets.

**Comment by iiPythonx** [comment]
> I went back to check and found it was a bug in my original code.

Good to know! I thought it might of been intentional but wasn't sure.

62f2e72 readds support for multiple `settings.json` files, and **also allows them to be reset using the same reset button** (with confirmation of course).

Also, I've noticed the codebase used quite a few `settingsFile ? "../" + settingsFile : "../settings.json"` statements. I have removed them and instead made the `settingsFile` variable default to `settings.json`. In my head, cleaner codebase means less work to maintain and easier to read through.

The dashboard still works fine, and the "non-settings JSON files" part of this PR still works (not allowing special characters or any filename not ending in `.json`). Let me know what you think of the commit, and if I should change anything else!

(the force push was me not realizing i pushed a change to `settings.sh.json` by accident, but it's reverted now)

**Comment by iiPythonx** [comment]
Closed due to inactivity, the commits should still be visible lass somebody want to implement any similar changes.

**Pull request closed without merging**
